name: Node Daily Cron Task

on:
  schedule:
    # UTC 02:00 → 北京时间 10:00 每天执行
    - cron: '0 2 * * *'
  # 支持网页手动 Run workflow 测试
  workflow_dispatch:

jobs:
  run-node-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm' # 缓存依赖，加速npm install

      - name: Install dependencies
        run: npm install

      - name: Run node script
        run: node index.js
        # 有密钥就取消下面注释
        # env:
        #   MY_TOKEN: ${{ secrets.MY_TOKEN }}
